/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ArrayHelper */

#ifndef _Included_ArrayHelper
#define _Included_ArrayHelper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ArrayHelper
 * Method:    square
 * Signature: ([D)I
 */
JNIEXPORT jint JNICALL Java_ArrayHelper_square
  (JNIEnv *, jclass, jdoubleArray);

#ifdef __cplusplus
}
#endif
#endif
